aligner/urls.py
from django.urls import path
from . views import WordListView, fr_sentence_view, eng_sentence_view, lat_sentence_view

app_name = 'aligner'

urlpatterns = [
    path('<int:chapter_number>/', WordListView.as_view(), name="word_list_view"),
    path('fr_sentence/<int:chapter_number>/<int:index>/', fr_sentence_view, name='fr_sentence_view'),
    path('en_sentence/<int:chapter_number>/<int:index>/', eng_sentence_view, name='eng_sentence_view' ),
    path('lat_sentence/<int:chapter_number>/<int:index>/', lat_sentence_view, name='lat_sentence_view' )
]

bodin_edition/urls.py
from django.contrib import admin
from django.urls import path,include
from aligner.views import home_view, ack_view, chapter_choices

urlpatterns = [
    path('admin/', admin.site.urls),
    path('aligner/', include('aligner.urls'), name='word_list_view'),
    path('acknowledgements/', ack_view, name='acknowledgements'),
    path('chapter_view/',chapter_choices, name='chapter_choices'),
    path('',home_view ,name='home')
]

aligner/models.py
from django.db import models
from email.policy import default

# Create your models here.
class FrenchWord(models.Model):
    chapter_number = models.CharField(max_length=30, null=True, blank=True, default='None Provided')
    word_text = models.CharField(max_length=30, default='None Provided')
    word_id = models.IntegerField()
    en_sent_id = models.IntegerField(null=True, blank=True, default='None Provided')
    la_sent_id = models.IntegerField(null=True, blank=True, default='None Provided')
    unaligned_id = models.CharField(max_length=30, null=True, blank=True, default='None Provided')
    en_sent_aligned = models.CharField(max_length=30, null=True, blank=True, default='None Provided')
    la_sent_aligned = models.CharField(max_length=30, null=True, blank=True, default='None Provided')
    lemma = models.CharField(max_length=30, null=True, blank=True, default='None Provided')
    PartOfSpeech = models.CharField(max_length=30, null=True, blank=True, default='None Provided')
    UDRelation = models.CharField(max_length=30, null=True, blank=True, default='None Provided')
    features = models.CharField(max_length=30, null=True, blank=True, default='None Provided')

    def __str__(self):
        return f'{self.word_text}'

class EnglishWord(models.Model):
    chapter_number = models.CharField(max_length=30, null=True, blank=True, default='None Provided')
    word_text = models.CharField(max_length=30, default='None Provided')
    word_id = models.IntegerField()
    sent_id = models.IntegerField()
    unaligned_id = models.CharField(max_length=30, null=True, blank=True, default='None Provided')
    sent_aligned = models.CharField(max_length=30, null=True, blank=True, default='None Provided')
    align_id = models.CharField(max_length=30, default='None Provided')
    lemma = models.CharField(max_length=30, null=True, blank=True, default='None Provided')
    PartOfSpeech = models.CharField(max_length=30, null=True, blank=True, default='None Provided')
    UDRelation = models.CharField(max_length=30, null=True, blank=True, default='None Provided')
    features = models.CharField(max_length=30, null=True, blank=True, default='None Provided')

    def __str__(self):
        return f'{self.word_text}'

class LatinWord(models.Model):
    chapter_number = models.CharField(max_length=30, null=True, blank=True, default='None Provided')
    word_text = models.CharField(max_length=30, default='None Provided')
    word_id = models.IntegerField()
    sent_id = models.IntegerField()
    unaligned_id = models.CharField(max_length=30, null=True, blank=True, default='None Provided')
    sent_aligned = models.CharField(max_length=30, null=True, blank=True, default='None Provided')
    align_id = models.CharField(max_length=30, default='None Provided')
    lemma = models.CharField(max_length=30, null=True, blank=True, default='None Provided')
    PartOfSpeech = models.CharField(max_length=30, null=True, blank=True, default='None Provided')
    UDRelation = models.CharField(max_length=30, null=True, blank=True, default='None Provided')
    features = models.CharField(max_length=30, null=True, blank=True, default='None Provided')

    def __str__(self):
        return f'{self.word_text}'

aligner/views.py
from itertools import chain
from django.shortcuts import get_object_or_404, render
from django.urls import reverse,reverse_lazy
from django.views.generic import ListView
from aligner.models import FrenchWord, EnglishWord, LatinWord
import json
import glob

## Helper objects
## Index look-up tables
def generateFrEnAlignedIndices(chapter_number):
    for FrEn in list(glob.glob("aligner\static\FrEn_aligned_indices*.json")):
        if str(chapter_number) in FrEn:
            fren_aligned_indices = open(FrEn)
            fren_aligned_data = json.load(fren_aligned_indices)
            return fren_aligned_data

def generateFrLaAlignedIndices(chapter_number):
    for FrLa in list(glob.glob("aligner\static\FrLa_aligned_indices*.json")):
        if str(chapter_number) in FrLa:
            frla_aligned_indices = open(FrLa)
            frla_aligned_data = json.load(frla_aligned_indices)
            return frla_aligned_data

# fren_aligned_indices = open(r'aligner\static\FrEn_aligned_indices.json')
# fren_aligned_data = json.load(fren_aligned_indices) 

# frla_aligned_indices = open(r'aligner\static\FrLa_aligned_indices.json')
# frla_aligned_data = json.load(frla_aligned_indices) 

# enla_aligned_indices = open(r'aligner\static\EnLa_aligned_indices.json')
# enla_aligned_data = json.load(enla_aligned_indices) 

## Unaligned/aligned dict updates
fr_unaligned_list = FrenchWord.objects.order_by().values('unaligned_id').distinct()
# fr_aligned_list = FrenchWord.objects.order_by().values('en_sent_id').distinct()

# for i in fr_unaligned_list:
#     for word in FrenchWord.objects.all():
#         if int(word.unaligned_id) == int(i['unaligned_id']):
#             for j in fr_aligned_list:
#                 if j['en_sent_id'] == int(word.en_sent_id):
#                     i['en_sent_id'] = j['en_sent_id']

# en_unaligned_list = EnglishWord.objects.order_by().values('unaligned_id').distinct()
# en_aligned_list = EnglishWord.objects.order_by().values('sent_id').distinct()

# for i in en_unaligned_list:
#     for word in EnglishWord.objects.all():
#         if int(word.unaligned_id) == int(i['unaligned_id']):
#             for j in en_aligned_list:
#                 if j['sent_id'] == int(word.sent_id):
#                     i['sent_id'] = j['sent_id']

# la_unaligned_list = LatinWord.objects.order_by().values('unaligned_id').distinct()
# la_aligned_list = LatinWord.objects.order_by().values('sent_id').distinct()

# for i in la_unaligned_list:
#     for word in LatinWord.objects.all():
#         if int(word.unaligned_id) == int(i['unaligned_id']):
#             for j in la_aligned_list:
#                 if j['sent_id'] == int(word.sent_id):
#                     i['sent_id'] = j['sent_id']

## Unaligned id string --> int
# fr_unaligned_int = [dict([a, int(x)] for a, x in b.items()) for b in FrenchWord.objects.order_by().values('unaligned_id').distinct()]
# en_unaligned_int = [dict([a, int(x)] for a, x in b.items()) for b in EnglishWord.objects.order_by().values('unaligned_id').distinct()]
# la_unaligned_int = [dict([a, int(x)] for a, x in b.items()) for b in LatinWord.objects.order_by().values('unaligned_id').distinct()]

def home_view(request):
    return render(request, 'aligner/home.html')

def ack_view(request):
    return render(request, 'aligner/acknowledgements.html')

def chapter_choices(request):
    return render(request, 'aligner/chapter_choices.html')

def fr_sentence_view(request, index, chapter_number):
    context_dict = {
        'index':str(index),
        'chapter_number':chapter_number,
        'unaligned_aligned':fr_unaligned_list,
        'french_sents': [dict([a, int(x)] for a, x in b.items()) for b in FrenchWord.objects.order_by().values('unaligned_id').distinct()],
        'french_words': FrenchWord.objects.all(),
        'english_sents': EnglishWord.objects.order_by().values('sent_id').distinct(),
        'english_words': EnglishWord.objects.all(),
        'latin_sents': LatinWord.objects.order_by().values('sent_id').distinct(),
        'latin_words': LatinWord.objects.all(),
        'fren_aligned_indices': generateFrEnAlignedIndices(chapter_number),
        'frla_aligned_indices': generateFrLaAlignedIndices(chapter_number)
    }
    return render(request, 'aligner/fr_sentence.html', context_dict)

def eng_sentence_view(request, index, chapter_number):
    fren_aligned_data_rev = [(t[1],t[0]) for t in generateFrEnAlignedIndices(chapter_number)]

    context_dict = {
        'index':index,
        'chapter_number':chapter_number,
        'french_sents': FrenchWord.objects.order_by().values('en_sent_id').distinct(),
        'french_words': FrenchWord.objects.all(),
        'english_sents': [dict([a, int(x)] for a, x in b.items()) for b in EnglishWord.objects.order_by().values('unaligned_id').distinct()],
        'english_words': EnglishWord.objects.all(),
        'latin_sents': LatinWord.objects.order_by().values('sent_id').distinct(),
        'latin_words': LatinWord.objects.all(),
        'fren_aligned_indices': fren_aligned_data_rev,
        'frla_aligned_indices': generateFrLaAlignedIndices(chapter_number)
    }
    return render(request, 'aligner/eng_sentence.html', context_dict)

def lat_sentence_view(request, index, chapter_number):
    frla_aligned_data_rev = [(t[1],t[0]) for t in generateFrLaAlignedIndices(chapter_number)]

    context_dict = {
        'index':index,
        'chapter_number':chapter_number,
        'french_sents': FrenchWord.objects.order_by().values('la_sent_id').distinct(),
        'french_words': FrenchWord.objects.all(),
        'english_sents': EnglishWord.objects.order_by().values('sent_id').distinct(),
        'english_words': EnglishWord.objects.all(),
        'latin_sents': [dict([a, int(x)] for a, x in b.items()) for b in LatinWord.objects.order_by().values('unaligned_id').distinct()],
        'latin_words': LatinWord.objects.all(),
        'fren_aligned_indices': generateFrEnAlignedIndices(chapter_number),
        'frla_aligned_indices': frla_aligned_data_rev
    }
    return render(request, 'aligner/lat_sentence.html', context_dict)

# Create your views here.
class WordListView(ListView):
    #model_list.html
    model = FrenchWord

    ## NEED TO LINK CHAPTER NUMBER FROM CHAPTER_CHOICES.HTML ##

    def makeFrAlignedUnaligned(self):
        fr_unaligned_list = FrenchWord.objects.filter(chapter_number=self.kwargs['chapter_number']).order_by().values('unaligned_id').distinct()
        fr_aligned_list = FrenchWord.objects.filter(chapter_number=self.kwargs['chapter_number']).order_by().values('en_sent_id').distinct()

        for i in fr_unaligned_list:
            for word in FrenchWord.objects.filter(chapter_number=self.kwargs['chapter_number']):
                if int(word.unaligned_id) == int(i['unaligned_id']):
                    for j in fr_aligned_list:
                        if j['en_sent_id'] == int(word.en_sent_id):
                            i['en_sent_id'] = j['en_sent_id']
        return fr_unaligned_list

    def makeEnLaAlignedUnaligned(self, word_object):
        unaligned_list = word_object.objects.filter(chapter_number=self.kwargs['chapter_number']).order_by().values('unaligned_id').distinct()
        aligned_list = word_object.objects.filter(chapter_number=self.kwargs['chapter_number']).order_by().values('sent_id').distinct()

        for i in unaligned_list:
            for word in word_object.objects.filter(chapter_number=self.kwargs['chapter_number']):
                if int(word.unaligned_id) == int(i['unaligned_id']):
                    for j in aligned_list:
                        if j['sent_id'] == int(word.sent_id):
                            i['sent_id'] = j['sent_id']
        return unaligned_list

    def get_context_data(self, **kwargs):
        context = super(WordListView, self).get_context_data(**kwargs)
        context['chapter_number'] = self.kwargs['chapter_number']
        context['fr_unaligned_aligned'] = self.makeFrAlignedUnaligned()
        context['en_unaligned_aligned'] = self.makeEnLaAlignedUnaligned(EnglishWord)
        context['la_unaligned_aligned'] = self.makeEnLaAlignedUnaligned(LatinWord)
        context['french_sents'] = FrenchWord.objects.filter(chapter_number=self.kwargs['chapter_number']).order_by().values('unaligned_id').distinct()
        context['french_words'] = FrenchWord.objects.filter(chapter_number=self.kwargs['chapter_number'])
        context['english_sents'] = EnglishWord.objects.filter(chapter_number=self.kwargs['chapter_number']).order_by().values('unaligned_id').distinct()
        context['english_words'] = EnglishWord.objects.filter(chapter_number=self.kwargs['chapter_number'])
        context['latin_sents'] = LatinWord.objects.filter(chapter_number=self.kwargs['chapter_number']).order_by().values('unaligned_id').distinct()
        context['latin_words'] = LatinWord.objects.filter(chapter_number=self.kwargs['chapter_number'])
        return context

aligner/templates/aligner/acknowledgements.html
{% block navbar %}
{% include 'aligner/navbar.html' %}
{% endblock navbar %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Acknowledgements</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://code.jquery.com/ui/1.13.0/jquery-ui.min.js" integrity="sha256-hlKLmzaRlE8SCJC1Kw8zoUbU8BxA+8kR3gseuKfMjxA=" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.13.0/jquery-ui.js"></script>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'aligner/index.css' %}">
</head>
<body>
    <h1 class="text-center">Acknowledgements</h1>
    <br>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tortor dignissim convallis aenean et tortor at risus viverra adipiscing. Libero enim sed faucibus turpis in eu. In nulla posuere sollicitudin aliquam. Lectus proin nibh nisl condimentum id venenatis a. Amet commodo nulla facilisi nullam vehicula ipsum a. Pellentesque dignissim enim sit amet venenatis urna cursus eget nunc. Vel quam elementum pulvinar etiam non quam lacus suspendisse. Pellentesque elit eget gravida cum sociis natoque penatibus et. Ornare arcu dui vivamus arcu felis bibendum. Donec ultrices tincidunt arcu non sodales neque sodales ut etiam. Habitasse platea dictumst quisque sagittis. Posuere urna nec tincidunt praesent. Mauris pharetra et ultrices neque ornare aenean. At varius vel pharetra vel turpis. Turpis egestas integer eget aliquet nibh praesent.</p>
</body>
</html>

aligner/templates/aligner/chapter_choices.html
{% block navbar %}
{% include 'aligner/navbar.html' %}
{% endblock navbar %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://code.jquery.com/ui/1.13.0/jquery-ui.min.js" integrity="sha256-hlKLmzaRlE8SCJC1Kw8zoUbU8BxA+8kR3gseuKfMjxA=" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.13.0/jquery-ui.js"></script>
    <script src="//mozilla.github.io/pdf.js/build/pdf.js"></script>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    {% load static %}
    <title>Chapters</title>
</head>
<body>
    <div class="container">
        <ul> <h5>Book1</h5>
            <li>
                <a href="{% url 'aligner:word_list_view' chapter_number=0 %}">Chapter 1</a>
            </li>
            <li>
                <a href="{% url 'aligner:word_list_view' chapter_number=1 %}">Chapter 2</a>
            </li>
            <li>
                <a href="{% url 'aligner:word_list_view' chapter_number=2 %}">Chapter 3</a>
            </li>
        </ul>
    </div>
    <div class="text-center">
        <div class="spinner-border" style="width: 6rem; height: 6rem;" role="status">
          <span class="sr-only">Loading...</span>
        </div>
    </div>
    {% load static %}
    <script src="{% static 'aligner/word_level.js' %}" charset="utf-8"></script>
    <script src="{% static 'aligner/pdf_interface.js' %}" charset="utf-8"></script>
    <script>
        $(document).ready(function(){
            $(".spinner-border").hide()
        })

        $(document).ready(function(){
            $('a').click(function(){
                $('.container').hide()
                $('.spinner-border').toggle()
            });
        });
    </script>
</body>
</html>

aligner/templates/aligner/frenchword_list.html
{% block navbar %}
{% include 'aligner/navbar.html' %}
{% endblock navbar %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Bodin Chapter View</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://code.jquery.com/ui/1.13.0/jquery-ui.min.js" integrity="sha256-hlKLmzaRlE8SCJC1Kw8zoUbU8BxA+8kR3gseuKfMjxA=" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.13.0/jquery-ui.js"></script>
    <script src="//mozilla.github.io/pdf.js/build/pdf.js"></script>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'aligner/index.css' %}">
  </head>
  <body>
    <div class="container">
      <div class="row">
          <div class="col-sm-4">
            <chap_fr>
              {% for d in fr_unaligned_aligned %}
                <a href="{% url 'aligner:fr_sentence_view' index=d.unaligned_id chapter_number=chapter_number %}">{{d.unaligned_id}}</a>
                <sentence sent_id={{d.unaligned_id}}>
                  {% for word in french_words %}
                    {% if word.unaligned_id == d.unaligned_id %}
                      <word word_id={{word.word_id}} en_sent_aligned={{word.en_sent_aligned}} la_sent_aligned="{{word.la_sent_aligned}}" lemma={{word.lemma}} PartOfSpeech={{word.PartOfSpeech}} UDRelation= {{word.UDRelation}} features= {{word.features}}>{{word.word_text}}</word>
                    {% endif %}
                  {% endfor %}
                </sentence>
              {% endfor %}
            </chap_fr>
          </div>
          <div class="col-sm-4">
            <chap_eng>
              {% for d in en_unaligned_aligned %}
                <a href="{% url 'aligner:eng_sentence_view' index=d.unaligned_id chapter_number=chapter_number %}">{{d.unaligned_id}}</a>
                <sentence en_id={{d.unaligned_id}}>
                {% for word in english_words %}
                  {% if word.unaligned_id == d.unaligned_id %}
                    <word word_id={{word.word_id}} align_id={{word.align_id}} sent_aligned={{word.sent_aligned}} lemma={{word.lemma}} PartOfSpeech={{word.PartOfSpeech}} UDRelation= {{word.UDRelation}} features= {{word.features}}>{{word.word_text}}</word>
                  {% endif %}
                {% endfor %}
                </sentence>
              {% endfor %}
            </chap_eng>
          </div>
          <div class="col-sm-4">
            <chap_lat>
              {% for d in la_unaligned_aligned %}
                <a href="{% url 'aligner:lat_sentence_view' index=d.unaligned_id chapter_number=chapter_number %}">{{d.unaligned_id}}</a>
                <sentence lat_id={{d.unaligned_id}}>
                {% for word in latin_words %}
                  {% if word.unaligned_id == d.unaligned_id %}
                    <word word_id={{word.word_id}} align_id={{word.align_id}} sent_aligned={{word.sent_aligned}} lemma={{word.lemma}} PartOfSpeech={{word.PartOfSpeech}} UDRelation= {{word.UDRelation}} features= {{word.features}}>{{word.word_text}}</word>
                  {% endif %}
                {% endfor %}
                </sentence>
              {% endfor %}
            </chap_lat>
          </div>
      </div>
    </div>
    <div class="fixed-bottom h-50 bg-secondary text-white">
      <div class="col text-center">
        <button type="button" class="btn btn-danger">Hide</button>
      </div>
      <br>
      <p>Click on a word.</p>
      <div class="row flexible-container">
        <div class="col-4 p-5 overflow-auto">
        </div>
        {% load static %}
        <div class="col-8">
          <canvas id="the-canvas"></canvas>
        </div>
      </div>
    </div>
    {% load static %}
    <script src="{% static 'aligner/word_level.js' %}" charset="utf-8"></script>
    <script src="{% static 'aligner/pdf_interface.js' %}" charset="utf-8"></script>
    <script>
      var french_pdf = "{% static 'aligner/french_grammar_resource.pdf'%}"
      var english_pdf = "{% static 'aligner/GrammarNotes.pdf' %}"
      var latin_pdf = "{% static 'aligner/F17-JMH-Latin-Grammar-3-1.pdf' %}" 
    </script>
  </body>
</html>

aligner/templates/aligner/home.html
{% block navbar %}
{% include 'aligner/navbar.html'%}
{% endblock navbar %}
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bodin's Six Bookes, Digital Edition</title>
    <link rel="icon" type="image/x-icon" href="{% static 'aligner/319793.jpg' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://code.jquery.com/ui/1.13.0/jquery-ui.min.js" integrity="sha256-hlKLmzaRlE8SCJC1Kw8zoUbU8BxA+8kR3gseuKfMjxA=" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.13.0/jquery-ui.js"></script>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'aligner/index.css' %}">
</head>
<body>
    <main role='main' class='container'>
        <h1 class="text-center">The Six Bookes of the Commonweale</h1>
        <h2 class="text-center">By Jean Bodin</h2>
        <br>
        <p>Ce édition digital des Six Livre de la République de Jean Bodin rassemble les tranductions en français (Bodin, 1576), en latin (Bodin, 1586), en anglais (Knolles, 1606) en une œuvre annotée pour les chercheurs qui poursuivent des recherches multilingues et comparatives</p>
        <br>
        <p>Hoc editio digitales Librorum Sex de republica Ioni Bodini Andegavensis ut corpus doctibus comparative et multilingua perscrutantibus adnotum translationes ex lingua Francogallica (Bodin, 1576), ex lingua Latina (Bodin, 1586), ex lingua Anglica conligat.</p>
        <br>
        <p>This digital edition of Jean Bodin's Six Bookes of the Commonweale collects the French (Bodin, 1576), Latin (Bodin, 1586), and English (Knolles, 1606) translations into an annotated corpus for scholars conducting multilingual comparative research.</p>
        <br>
    </main>
    <footer class="fixed-bottom text-center">
        <div class='container'>
            <span class= 'text-muted'>Assembled by Peter Nadel</span>
        </div>
    </footer>
</body>
</html>